AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MemosInstance: 
      Type: AWS::RDS::DBInstance
      Properties: 
        DBSecurityGroups: 
          - 
            Ref: "DbSecurityByEC2SecurityGroup"
        AllocatedStorage: "5"
        DBInstanceClass: "db.t2.micro"
        Engine: "MySQL"
        MasterUsername: "root"
        MasterUserPassword: "password"
      DeletionPolicy: "Snapshot"
  DbSecurityByEC2SecurityGroup: 
      Type: AWS::RDS::DBSecurityGroup
      Properties: 
        GroupDescription: "Ingress for Amazon EC2 security group"
        DBSecurityGroupIngress: 
          - 
            EC2SecurityGroupId: "subnet-03bf4ec35cff443e8"
            EC2SecurityGroupOwnerId: "522935911499"
