MemosRdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to client host
        VpcId: 
          Ref: MemosVPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        Tags: 
        - Key: "Name"
          Value: "MemosRdsSecurityGroup"
  MemosInstance: 
    Type: AWS::RDS::DBInstance
    Properties: 
      DBSecurityGroups: 
        - 
          Ref: "MemosRdsSecurityGroup"
      AllocatedStorage: "5"
      DBInstanceClass: "db.t2.micro"
      Engine: MySQL
      EngineVersion: "5.7.22"
      MasterUsername: "root"
      MasterUserPassword: "password"
    DeletionPolicy: "Snapshot"