AWSTemplateFormatVersion: "2010-09-09"
Description: "Ver4"

Parameters:
  # SSH用キーペアの指定
  KeyPair:
    Description: KeyPair Name
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: test-vpc

  # パブリックサブネット
  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.10.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: public-subnet-1a

  PublicSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: public-subnet-1c

  # プライベートサブネット
  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.20.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: private-subnet-1a

  PrivateSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.30.0/24
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: private-subnet-1c

  # ルートテーブル
  RouteTable:
    Type:  AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: public-route

  # インターネットゲートウェイ
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: igw

  # インターネットゲートウェイとルートテーブルの関連付け
  RouteInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  # サブネットとルートテーブルの関連付け
  RouteLocal1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1a
      RouteTableId: !Ref RouteTable

  RouteLocal1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1c
      RouteTableId: !Ref RouteTable

  # VPCGatewayAttachment
  AwsCfNewwProject:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  # WEBSV用セキュリティグループ
  WEBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: web-sg
      GroupName: web-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIpv6: ::/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIpv6: ::/0
      Tags:
        - Key: Name
          Value: web-sg

  # RDS用セキュリティグループ
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: rds-sg
      GroupName: rds-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref WEBSecurityGroup
      Tags:
        - Key: Name
          Value: rds-sg

  # ALB用セキュリティグループ
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: alb-sg
      GroupName: alb-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIpv6: ::/0
      Tags:
        - Key: Name
          Value: alb-sg

  # EC2インスタンス（WEB)
  EC2Instance01:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref PublicSubnet1a
      InstanceType: t2.micro
      AvailabilityZone: ap-northeast-1a
      KeyName: !Ref KeyPair
      Monitoring: false
      ImageId: ami-068a6cefc24c301d2
      InstanceInitiatedShutdownBehavior: stop
      SecurityGroupIds:
        - !Ref WEBSecurityGroup
      Tags:
        - Key: Name
          Value: SV#1

  # EC2インスタンス（WEB)
  EC2Instance02:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref PublicSubnet1c
      InstanceType: t2.micro
      AvailabilityZone: ap-northeast-1c
      KeyName: !Ref KeyPair
      Monitoring: false
      ImageId: ami-068a6cefc24c301d2
      InstanceInitiatedShutdownBehavior: stop
      SecurityGroupIds:
        - !Ref WEBSecurityGroup
      Tags:
        - Key: Name
          Value: SV#2