AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MemosVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: "Name"
        Value: "MemosVpc"
  MemosPubSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: MemosVPC
      CidrBlock: 10.0.10.0/24
      AvailabilityZone: "ap-northeast-1a"
      Tags:
      - Key: "Name"
        Value: "MemosPubSubnet1a"
  MemosPriSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: MemosVPC
      CidrBlock: 10.0.20.0/24
      AvailabilityZone: "ap-northeast-1a"
      Tags:
      - Key: "Name"
        Value: "MemosPriSubnet1a"
  MemosIgw:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
      - Key: "Name"
        Value: "MwmosIgw"
  MemosIgwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: MemosVPC
      InternetGatewayId:
        Ref: MemosIgw
  MemosRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: MemosVPC
      Tags:
      - Key: "Name"
        Value: "MemosRouteTable"
  MemosRouteInterNet:
    Type: AWS::EC2::Route
    DependsOn: MemosIgwAttach
    Properties:
      RouteTableId:
        Ref: MemosRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: MemosIgw
  MemosSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: MemosPubSubnet1a
      RouteTableId:
        Ref: MemosRouteTable
  MemosInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to client host
        VpcId: 
          Ref: MemosVPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        Tags: 
        - Key: "Name"
          Value: "MemosInstanceSecurityGroup"
  MemosDBsubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: description
      SubnetIds: 
        - subnet-7b5b4112
        - subnet-7b5b4115
      Tags: 
        - 
          Key: "Name"
          Value: "MemosDBsubnetGroup"
    

  MemosDB:  
    Resources: 
      DBinstance: 
        Type: AWS::RDS::DBInstance
        Properties: 
          DBSecurityGroups: 
            - 
              Ref: "DbSecurityByEC2SecurityGroup"
          DBName: MemosDB
          AllocatedStorage: "20"
          DBInstanceClass: "db.2.micro"
          Engine: "MySQL"
          MasterUsername: "root"
          MasterUserPassword: "password"

        DeletionPolicy: "Snapshot"
  DbSecurityByEC2SecurityGroup: 
    Type: AWS::RDS::DBSecurityGroup
    Properties: 
      GroupDescription: "Ingress for Amazon EC2 security group"
      DBSecurityGroupIngress: 
        - 
          EC2SecurityGroupId: "sg-b0ff1111"
          EC2SecurityGroupOwnerId: "111122223333"
        - 
          EC2SecurityGroupId: "sg-ffd722222"
          EC2SecurityGroupOwnerId: "111122223333"
